### ISSUE TITLE
CommonJS Conversion

### ISSUE THREAD

**Issue by Mirrage0** [M3rcena/m3rcena-weky#1]
As the title suggests, is there a version/way to convert from ESM to CommonJS? I have tried to convert myself and ran into errors. Plus I think a few others might have came into the issue with ESM syntax with a CommonJS codebase 👍

**Comment by M3rcena** [comment]
I can implement it. Most likely until next week it will be published.

**Comment by M3rcena** [comment]
@Mirrage0 can you check if the new update I just pushed works?

**Comment by M3rcena** [comment]
> Sure, ill give it a shot and let you know how it goes. Give me a day or two, im converting from mongoDB to SQLite and want to get that sorted before working on commands again 👍

@Mirrage0 also if any command does not work or give error tell me to check it out!

**Comment by M3rcena** [comment]
@Mirrage0 I runned some test, it seems to work for me locally, whenever you run your tests let me know!

**Comment by M3rcena** [comment]
@Mirrage0 I found some issue, I fixed 90% of them, I will fix everything else tomorrow.

**Comment by M3rcena** [comment]
> Couple i tried do work but most people use v14.14.1, so MessageEmbed is now EmbedBuilder and MessageButton is now ButtonBuilder, I can do the little changes myself as its a personal thing.
> Is it possible by any chance to have a version that is compatible with slash commands, ill see what i can do about that one if you can't get to it. Could keep a version for prefix like "djs-games-prefix" and one for slash like "djs-games-slash", just a thought for in the future. (i would def be a sponsor but don't have paypal as the fees are annoying, if you had a stripe donation link or something, hell I'd do it you deserve it)

Hi @Mirrage0, you are so kind. But there is no need for donations, I am just a kid which loves to do such a things. Adding slash commands is already on my to-do, also I show yesterday the issues with the embeds and the button and I already began fixing. I will finish the today most likely and at the end of the week I will also have slash command support

**Comment by M3rcena** [comment]
@Mirrage0 do you have by any chance discord so we can talk from there easier?
